version: '3.9'

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports: 
    - 3306:3306
  
  web:
    build:
      context: ./backend/
      dockerfile: Dockerfile.nginx
    volumes:
    - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/backapp.conf
    - public-data:/backapp/public
    - tmp-data:/backapp/tmp
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    #environment:
    #  - EDITOR=vim
    tty: true
    stdin_open: true
    depends_on:
    - db
    build: 
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
    - ./backend:/backapp
    - public-data:/backapp/public
    - tmp-data:/backapp/tmp
    - log-data:/backapp/log
    command: bundle exec puma -C config/puma.rb
    #command: bundle exec puma -C config/puma.rb -e production
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
    - ./frontend:/frontapp
    command: 'npm run dev'
    ports:
    - 3000:3000

volumes:
  mysql_data:
    driver: local
  public-data:
  tmp-data:
  log-data:
