version: '3'

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./backend/db/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports: 
    - 3307:3306
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  backend:
    tty: true
    stdin_open: true
    depends_on:
    - db
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
    - 5000:3000
    volumes:
    - ./backend:/backapp
    command: rails server -b 0.0.0.0
    networks:
      app_net:
        ipv4_address: '172.20.0.3'
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
    - ./frontend:/frontapp
    command: 'npm run dev'
    ports:
    - "3000:3000"
    networks:
      app_net:
        ipv4_address: '172.20.0.4'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24