version: '3'

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./backend/db/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports: 
    - 3307:3306
  
  web:
    build:
      context: ./backend/
      dockerfile: Dockerfile.nginx
    volumes:
    - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/backapp.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    tty: true
    stdin_open: true
    depends_on:
    - db
    build: 
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
    - ./backend:/backapp
    command: bundle exec puma -C config/puma.rb
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
    - ./frontend:/frontapp
    command: 'npm run dev'
    ports:
    - "3000:3000"
