import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export const TitleHead = ()=>{
    return (
        <div>
            <Head>
            <title>Procedurey</title>
            <meta charSet="utf-8" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}