version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    working_directory: ~/Portfolio/backend
    steps:
      - checkout:
          path: ~/Portfolio
      - ruby/install-deps

  rspec:
    docker:
      - image: cimg/ruby:3.1.2-node
        environment: 
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: "root"
          DB_PASSWORD: ""
      - image: cimg/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    
    working_directory: ~/Portfolio/backend
        
    steps:
      - checkout:
          path: ~/Portfolio
      - ruby/install-deps

      # restore gem from cache
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "~/Portfolio/backend/Gemfile.lock" }}
            - gem-cache-v1-
          working_directory: ~/Portfolio/backend

      # gem install
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/Portfolio/backend

      - save_cache:
          key: gem-cache-v1-{{ checksum "~/Portfolio/backend/Gemfile.lock" }}
          paths:
            - ~/Portfolio/backend/vendor/bundle
          working_directory: ~/Portfolio/backend

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/Portfolio/backend
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/Portfolio/backend

      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/Portfolio/backend

      # run tests
      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/Portfolio/backend

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/Portfolio/tmp/screenshots

  jest:
    docker:
      - image: cimg/node:18.0.0
        environment:
          NODE_ENV: test

    working_directory: ~/Portfolio

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/Portfolio/frontend/package.json" }}
          working_directory: ~/Portfolio/frontend
      - run:
          name: install-packages
          command: npm install --legacy-peer-deps
          no_output_timeout: 30m
          working_directory: ~/Portfolio/frontend
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/Portfolio/frontend/package.json" }}
          working_directory: ~/Portfolio/frontend
      - run:
          name: test
          command: npm run test
          working_directory: ~/Portfolio/frontend

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - rspec:
          filters:
            branches:
              only: main
          requires:
            - build
      - jest:
          filters:
            branches:
              only: main
      - aws-ecr/build-and-push-image:
          name: "ecr-push-rails"
          requires:
            - rspec
            - jest
          filters:
            branches:
              only: main
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          push-image: true
          region: '${AWS_REGION}'
          registry-id: AWS_ACCOUNT_ID
          repo: "portfolio-backend"
          tag: "latest"
          path: ./backend/
      - aws-ecr/build-and-push-image:
          name: "ecr-push-react"
          requires:
            - rspec
            - jest
          filters:
            branches:
              only: main
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          push-image: true
          region: '${AWS_REGION}'
          registry-id: AWS_ACCOUNT_ID
          repo: "portfolio-frontend"
          tag: "latest"
          path: ./frontend/
      - aws-ecr/build-and-push-image:
          name: "ecr-push-nginx"
          requires:
            - rspec
            - jest
          filters:
            branches:
              only: main
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          push-image: true
          region: '${AWS_REGION}'
          registry-id: AWS_ACCOUNT_ID
          repo: "portfolio-web"
          tag: "latest"
          path: ./backend/nginx/
      - aws-ecs/deploy-service-update:
          name: "ecs-deploy-rails"
          requires:
            - ecr-push-rails
          family: "portfolio-backend"
          service-name: "portfolio-backend-service"
          cluster: "portfolio-cluster"
          container-image-name-updates: "container=rails,tag=latest"
      - aws-ecs/deploy-service-update:
          name: "ecs-deploy-react"
          requires:
            - ecr-push-react
          family: "portfolio-frontend"
          service-name: "portfolio-frontend-service"
          cluster: "portfolio-cluster"
          container-image-name-updates: "container=portfolio-frontend-container,tag=latest"
      - aws-ecs/deploy-service-update:
          name: "ecs-deploy-nginx"
          requires:
            - ecr-push-nginx
            - ecs-deploy-rails
          family: "portfolio-backend"
          service-name: "portfolio-backend-service"
          cluster: "portfolio-cluster"
          container-image-name-updates: "container=nginx,tag=latest"


