import styled from "styled-components"
import Head from 'next/head'
import {Header} from "./header"
import {Footer} from "./footer"
import type {ReactNode} from "react"
import { useMediaQuery } from "react-responsive"

type Props = {
    children: ReactNode;
}

const Wrapper = styled.div`
display: flex;
flex-flow: column;
min-height: 200vh;

main {
    flex: 1;
    }
`

export const Layout = (props:Props)=>{
    const PC:boolean = useMediaQuery({query:'(min-width: 960px)'})
    const Tablet:boolean = useMediaQuery({query:'(min-width: 520px) and (max-width: 959px)'})
    const Mobile:boolean = useMediaQuery({query: '(max-width: 519px)'})

    return (
        <>
            <Head>
            <title>Dailylifey</title>
            <meta charSet="utf-8" />
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width,initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
            <Header />
            <main>{props.children}</main>
            <Footer />
            </Wrapper>
        </>
    )
}

export default Layout