import styled from "styled-components"
import Head from 'next/head'
import {Header} from "./header"
import {Footer} from "./footer"

export const Layout = (props:any)=>{
    return (
        <>
            <Head>
            <title>Procedurey</title>
            <meta charSet="utf-8" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div>
                {props.children}
            </div>
            <Footer />
        </>
    )
}

